id: get_file_endpoint_history_-_carbon_black_response
fromversion: 3.5.0
system: true
version: -1
name: Get File Endpoint History - Carbon Black Response
description: Hunt for malicious indicators using Carbon Black
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: edc8b672-13e8-48fa-87c9-594118876ac4
    type: start
    task:
      id: edc8b672-13e8-48fa-87c9-594118876ac4
      version: -1
      name: ""
      description: Playbook start point
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: ad7dff09-2373-43ba-8a87-645fa98ca5cb
    type: regular
    task:
      id: ad7dff09-2373-43ba-8a87-645fa98ca5cb
      version: -1
      name: Hunt MD5 Hash
      description: Search Carbon Black for the specified MD5 hash(es)
      scriptName: CBFindHash
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      md5:
        complex:
          root: inputs
          accessor: Hash
    results:
    - found_file_locations
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 356,
          "y": 611
        }
      }
  "2":
    id: "2"
    taskid: 504da0d8-d8f5-4273-8954-d5d333dc5ca1
    type: condition
    task:
      id: 504da0d8-d8f5-4273-8954-d5d333dc5ca1
      version: -1
      name: Is Carbon Black enabled?
      description: Is Carbon Black enabled?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    scriptarguments:
      value:
        simple: ${modules(val.brand == 'carbonblack' && val.state == 'active')}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: carbonblack
                accessor: brand
            iscontext: true
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    id: "3"
    taskid: 108ba97d-b9da-4162-808d-025b5f6b7986
    type: title
    task:
      id: 108ba97d-b9da-4162-808d-025b5f6b7986
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 937
        }
      }
  "4":
    id: "4"
    taskid: 4dc64cf1-acb2-47b5-87c8-88e0e90e6c11
    type: condition
    task:
      id: 4dc64cf1-acb2-47b5-87c8-88e0e90e6c11
      version: -1
      name: Do we have files to hunt?
      description: Do we have files to hunt?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "1"
    scriptarguments:
      value:
        complex:
          root: inputs
          accessor: Hash
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: inputs
                accessor: Hash
            iscontext: true
    view: |-
      {
        "position": {
          "x": 356,
          "y": 371
        }
      }
  "5":
    id: "5"
    taskid: 09e186f8-7d8d-4f32-84f8-5960a2e943af
    type: regular
    task:
      id: 09e186f8-7d8d-4f32-84f8-5960a2e943af
      version: -1
      name: Set hostname
      description: Set hostname
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      append: {}
      key:
        simple: Endpoint.Hostname
      value:
        complex:
          root: found_file_locations
          transformers:
          - operator: string.replaceMatch
            args:
              regex:
                value:
                  simple: '{".*": \[".*", "(.*)"]}'
              replaceWith:
                value:
                  simple: $1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 356,
          "y": 772
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "2_3_#default#": 0.3,
      "2_4_yes": 0.5,
      "4_1_yes": 0.5,
      "4_3_#default#": 0.4
    },
    "paper": {
      "dimensions": {
        "height": 952,
        "width": 686,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Hash
  value:
    complex:
      root: File
      accessor: MD5
  required: false
  description: MD5 Hash
outputs:
- contextPath: Endpoint.Hostname
  description: The device hostname
  type: string
- contextPath: Endpoint
  description: The endpoint
  type: unknown
releaseNotes: "-"